### ISSUE TITLE
Change age-specific t-tests to single ANOVA

### ISSUE THREAD

**Issue by mckenziephagen** [uw-psych/psych532-ToM-project#13]
Discussed with @carolylu via Slack - a single ANOVA might be more appropriate than multiple t-tests. @guoziqi1275 , thoughts?

**Comment by guoziqi1275** [comment]
Sorry, I might be a little behind, but what are we talking about here?
Best,
Ziqi

McKenzie Paige Hagen ***@***.***>于2024年4月25日 周四10:53写道：

**Comment by mckenziephagen** [comment]
Oh, no, I was just very vague, sorry! Right now, what we're doing is doing a bunch t-tests to test gender differences at each age individually. I *think* an ANOVA might be more appropriate here. 

Or, if we stick with multiple t-tests, we should definitely be controlling for multiple comparisons (I know nothing is significant regardless, but it'd still be good to do).
